"""MCP Server Wrapper — 将本地 skill 自动封装为 MCP Server。

渐进信任 Phase 3: 新安装/创建的 skill 可自动生成一个标准
MCP Server 脚本（stdio 传输），使其能被任何 MCP 客户端调用。

生成的 mcp_server.py 是独立可运行的:
    python skills/my_skill/mcp_server.py

也可注册到 data/mcp_servers.json 中被 MCPClientAdapter 自动加载。
"""

import json
import pathlib
import textwrap
from typing import Any

from logs import get_logger

logger = get_logger("mcp-wrapper")

_SKILLS_DIR = pathlib.Path(__file__).parent

# MCP Server 模板 — 生成独立的 stdio MCP Server
_MCP_SERVER_TEMPLATE = textwrap.dedent('''\
#!/usr/bin/env python3
"""MCP Server for skill: {skill_name}

Auto-generated by LucidMind MCP Wrapper.
Protocol: JSON-RPC 2.0 over stdio (MCP 2024-11-05)

Usage:
    python {script_path}
"""

import asyncio
import importlib.util
import json
import sys
import os

# 确保项目根目录在 path 中
_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

SKILL_DIR = os.path.dirname(os.path.abspath(__file__))
ENTRY_FILE = os.path.join(SKILL_DIR, "{entry}")
MODULE_NAME = "skills.{dir_name}.{module_name}"

SERVER_INFO = {{
    "name": "{skill_name}-mcp-server",
    "version": "{version}",
}}

CAPABILITIES = {{
    "tools": {{}},
}}


def _load_adapter():
    """加载 skill 的 Adapter 实例。"""
    spec = importlib.util.spec_from_file_location(MODULE_NAME, ENTRY_FILE)
    if not spec or not spec.loader:
        raise RuntimeError(f"Cannot load module: {{ENTRY_FILE}}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    for attr_name in dir(mod):
        if attr_name.endswith("Adapter") and attr_name != "ToolPort":
            cls = getattr(mod, attr_name)
            if hasattr(cls, "list_tools") and hasattr(cls, "execute"):
                return cls()
    raise RuntimeError("No Adapter class found in skill")


class MCPServer:
    """Minimal MCP Server (stdio transport)."""

    def __init__(self):
        self._adapter = _load_adapter()
        self._tools = self._adapter.list_tools()

    async def handle_request(self, msg: dict) -> dict | None:
        method = msg.get("method", "")
        req_id = msg.get("id")
        params = msg.get("params", {{}})

        if method == "initialize":
            return {{
                "jsonrpc": "2.0", "id": req_id,
                "result": {{
                    "protocolVersion": "2024-11-05",
                    "capabilities": CAPABILITIES,
                    "serverInfo": SERVER_INFO,
                }},
            }}

        if method == "notifications/initialized":
            return None  # notification, no response

        if method == "tools/list":
            tools = []
            for t in self._tools:
                fn = t.get("function", {{}})
                tools.append({{
                    "name": fn.get("name", ""),
                    "description": fn.get("description", ""),
                    "inputSchema": fn.get("parameters", {{"type": "object", "properties": {{}}}}),
                }})
            return {{
                "jsonrpc": "2.0", "id": req_id,
                "result": {{"tools": tools}},
            }}

        if method == "tools/call":
            tool_name = params.get("name", "")
            arguments = params.get("arguments", {{}})
            try:
                result = await self._adapter.execute(tool_name, arguments)
                is_error = not result.get("success", False)
                content_text = json.dumps(
                    result.get("result", result.get("error", "")),
                    ensure_ascii=False, default=str,
                )
                return {{
                    "jsonrpc": "2.0", "id": req_id,
                    "result": {{
                        "content": [{{"type": "text", "text": content_text}}],
                        "isError": is_error,
                    }},
                }}
            except Exception as e:
                return {{
                    "jsonrpc": "2.0", "id": req_id,
                    "result": {{
                        "content": [{{"type": "text", "text": str(e)}}],
                        "isError": True,
                    }},
                }}

        # Unknown method
        return {{
            "jsonrpc": "2.0", "id": req_id,
            "error": {{"code": -32601, "message": f"Method not found: {{method}}"}},
        }}

    async def run(self):
        """Read JSON-RPC from stdin, write to stdout."""
        loop = asyncio.get_event_loop()
        reader = asyncio.StreamReader()
        protocol = asyncio.StreamReaderProtocol(reader)
        await loop.connect_read_pipe(lambda: protocol, sys.stdin)

        writer_transport, writer_protocol = await loop.connect_write_pipe(
            asyncio.streams.FlowControlMixin, sys.stdout
        )
        writer = asyncio.StreamWriter(
            writer_transport, writer_protocol, reader, loop
        )

        while True:
            line = await reader.readline()
            if not line:
                break
            try:
                msg = json.loads(line.decode().strip())
            except json.JSONDecodeError:
                continue

            resp = await self.handle_request(msg)
            if resp is not None:
                out = json.dumps(resp, ensure_ascii=False) + "\\n"
                writer.write(out.encode())
                await writer.drain()


if __name__ == "__main__":
    server = MCPServer()
    asyncio.run(server.run())
''')


def generate_mcp_server(skill_name: str) -> dict[str, Any]:
    """为指定 skill 生成 MCP Server 脚本。

    Args:
        skill_name: skills/ 下的子目录名

    Returns:
        {"success": bool, "path": str|None, "error": str|None}
    """
    skill_dir = _SKILLS_DIR / skill_name
    manifest_path = skill_dir / "manifest.json"

    if not manifest_path.exists():
        return {"success": False, "error": f"Skill {skill_name} 不存在或无 manifest.json"}

    try:
        manifest = json.loads(manifest_path.read_text("utf-8"))
    except Exception as e:
        return {"success": False, "error": f"读取 manifest 失败: {e}"}

    entry = manifest.get("entry", "main.py")
    entry_path = skill_dir / entry
    if not entry_path.exists():
        return {"success": False, "error": f"入口文件不存在: {entry}"}

    version = manifest.get("version", "1.0.0")
    module_name = entry_path.stem  # "main"
    script_path = f"skills/{skill_name}/mcp_server.py"

    content = _MCP_SERVER_TEMPLATE.format(
        skill_name=skill_name,
        script_path=script_path,
        entry=entry,
        dir_name=skill_name,
        module_name=module_name,
        version=version,
    )

    server_path = skill_dir / "mcp_server.py"
    server_path.write_text(content, encoding="utf-8")
    # 设置可执行权限
    server_path.chmod(0o755)

    logger.info(f"MCP Server 已生成: {server_path}")
    return {"success": True, "path": str(server_path)}


def register_mcp_server(skill_name: str, auto_generate: bool = True) -> dict[str, Any]:
    """将 skill 的 MCP Server 注册到 data/mcp_servers.json。

    如果 mcp_server.py 不存在且 auto_generate=True，先自动生成。

    Args:
        skill_name: skill 名称
        auto_generate: 是否自动生成 mcp_server.py

    Returns:
        {"success": bool, "config": dict|None, "error": str|None}
    """
    import sys

    skill_dir = _SKILLS_DIR / skill_name
    server_script = skill_dir / "mcp_server.py"

    if not server_script.exists():
        if auto_generate:
            result = generate_mcp_server(skill_name)
            if not result.get("success"):
                return result
        else:
            return {"success": False, "error": f"mcp_server.py 不存在: {skill_name}"}

    # 构建 MCP 配置
    config = {
        "name": f"skill-{skill_name}",
        "transport": "stdio",
        "command": sys.executable,
        "args": [str(server_script)],
        "auto_generated": True,
    }

    # 读取现有配置
    config_path = _SKILLS_DIR.parent / "data" / "mcp_servers.json"
    config_path.parent.mkdir(parents=True, exist_ok=True)

    servers = []
    if config_path.exists():
        try:
            servers = json.loads(config_path.read_text("utf-8"))
            if not isinstance(servers, list):
                servers = []
        except Exception:
            servers = []

    # 去重：移除同名的旧配置
    servers = [s for s in servers if s.get("name") != config["name"]]
    servers.append(config)

    config_path.write_text(
        json.dumps(servers, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    logger.info(f"MCP Server 已注册: {config['name']} → {server_script}")
    return {"success": True, "config": config}


def unregister_mcp_server(skill_name: str) -> dict[str, Any]:
    """从 data/mcp_servers.json 移除 skill 的 MCP Server 配置。"""
    config_path = _SKILLS_DIR.parent / "data" / "mcp_servers.json"
    server_name = f"skill-{skill_name}"

    if not config_path.exists():
        return {"success": True, "message": "配置文件不存在，无需移除"}

    try:
        servers = json.loads(config_path.read_text("utf-8"))
        if not isinstance(servers, list):
            return {"success": True, "message": "配置格式异常，已跳过"}

        original_count = len(servers)
        servers = [s for s in servers if s.get("name") != server_name]

        if len(servers) == original_count:
            return {"success": True, "message": f"未找到 {server_name} 配置"}

        config_path.write_text(
            json.dumps(servers, ensure_ascii=False, indent=2), encoding="utf-8"
        )
        logger.info(f"MCP Server 已注销: {server_name}")
        return {"success": True, "message": f"已移除 {server_name}"}
    except Exception as e:
        return {"success": False, "error": str(e)}
